name: Deploy to AWS Lightsail Container

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string

env:
  image_tag: ${{inputs.image_tag}}

jobs:
  deploy-to-aws-lightsail:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Install lightsailctl
        run: |
          curl -L "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          chmod +x /usr/local/bin/lightsailctl

      - name: Write AWS access credentials
        run: |
          mkdir -p ~/.aws
          cat <<"EOF" > ~/.aws/credentials
          [default]
          aws_access_key_id=${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key=${{secrets.AWS_SECRET_ACCESS_KEY}}
          EOF

      - name: Debug image_tag
        run: |
          echo "Using image tag: ${{ env.image_tag }}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull Docker image from GHCR
        run: |
          docker pull ${{ env.image_tag }}

      - name: Set short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Push Docker image to Lightsail Container Service
        run: |
          aws lightsail push-container-image \
            --region ${{ vars.AWS_REGION }} \
            --service-name ${{ vars.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --label ${{ vars.AWS_LIGHTSAIL_CONTAINER_NAME }}-${{ env.short_sha }} \
            --image ${{ env.image_tag }}

      - name: Get latest Lightsail image URL
        id: get-image-url
        run: |
          IMAGE_URL=$(aws lightsail get-container-images \
            --region ${{ vars.AWS_REGION }} \
            --service-name ${{ vars.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --query 'containerImages[0].image' \
            --output text)
          echo "LIGHTSAIL_IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
          echo "Lightsail Image URL: $IMAGE_URL"

      - name: Create Lightsail deployment configuration JSON
        run: |
          cat <<EOF > container-deployment.json
          {
            "containers": {
              "${{ vars.AWS_LIGHTSAIL_CONTAINER_NAME }}": {
                "image": "${{ env.LIGHTSAIL_IMAGE_URL }}",
                "ports": {
                  "${{ secrets.AWS_LIGHTSAIL_CONTAINER_PORT }}": "HTTP"
                }
              }
            },
            "publicEndpoint": {
              "containerName": "${{ vars.AWS_LIGHTSAIL_CONTAINER_NAME }}",
              "containerPort": ${{ secrets.AWS_LIGHTSAIL_CONTAINER_PORT }},
              "healthCheck": {
                "path": "/actuator/health",
                "successCodes": "200-399",
                "timeoutSeconds": 5,
                "intervalSeconds": 10,
                "unhealthyThreshold": 2,
                "healthyThreshold": 2
              }
            }
          }
          EOF

      - name: Create new Lightsail Container Service deployment
        run: |
          aws lightsail create-container-service-deployment \
            --region ${{ vars.AWS_REGION }} \
            --service-name ${{ vars.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --cli-input-json file://container-deployment.json