name: Build and Push to GHCR

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      GHCR_IMAGE_NAME:
        required: true
        type: string
      GHCR_IMAGE_TAG:
        required: true
        type: string

    outputs:
      image_tag:
        description: "The full Docker image tag pushed to GHCR"
        value: ${{ jobs.build-image-and-push-to-ghcr.outputs.image_tag }}

env:
  JAVA_VERSION: '21'
  GHCR_IMAGE_NAME: ${{inputs.GHCR_IMAGE_NAME}}
  GHCR_IMAGE_TAG: ${{inputs.GHCR_IMAGE_TAG}}

jobs:
  build-image-and-push-to-ghcr:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      image_tag: ${{ steps.export-tag.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application.yml with secrets
        run: |
          mkdir -p src/main/resources
          cat <<"EOF" > src/main/resources/application.yml
          spring:
            application:
              name: sync-dev
            datasource:
              url: "${{ secrets.DB_URL }}"
              driver-class-name: org.postgresql.Driver
            jpa:
              hibernate:
                ddl-auto: validate
              show-sql: false
              properties:
                hibernate:
                  format_sql: true
          cors:
            allowed-origins:
              - http://localhost:3000
              - "${{ vars.ALLOWED_ORIGINS }}"
          EOF

      - name: Build Spring Boot application with Gradle
        run: ./gradlew bootJar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image to GHCR
        id: build-push-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:${{ env.GHCR_IMAGE_TAG }}
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:${{ github.sha }}
          outputs: type=image,names=ghcr.io/${{ env.GHCR_IMAGE_NAME }}:${{ env.GHCR_IMAGE_TAG }},ghcr.io/${{ env.GHCR_IMAGE_NAME }}:${{ github.sha }}
      - name: Set image tag output
        id: export-tag
        run: echo "image_tag=ghcr.io/${{ env.GHCR_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Verify Docker image push (optional)
        run: echo "Docker image ghcr.io/${{ env.GHCR_IMAGE_NAME }}:${{ github.sha }} pushed successfully to GHCR!"
